"""Round-trip tests for review.yaml multi-document format and parsing.

Covers build_review (emits multi-doc), parse_review (reads multi-doc and legacy
single-list), and the format's backward compatibility.
"""
from __future__ import annotations

from pathlib import Path

from book_meta_fix.models import BookMeta, Confidence, Diagnosis, Verdict
from book_meta_fix.review import build_review, parse_review


def _meta(calibre_id: int, title: str = "T", author: str = "A") -> BookMeta:
	return BookMeta(calibre_id=calibre_id, title=title, authors=[author], path=f"/lib/A/{title} ({calibre_id})")


def _diag(category: str = "C2", verdict: Verdict = Verdict.NEEDS_REVIEW) -> Diagnosis:
	return Diagnosis(category=category, reason="r", confidence=Confidence.HIGH, verdict=verdict)


class TestBuildReviewFormat:
	def test_emits_multi_document_with_separators(self):
		items = [(_meta(1), _diag(), None, None), (_meta(2), _diag(), None, None)]
		out = build_review(items)
		# Each entry prefixed by its own --- document marker.
		assert out.count("---") == 2
		# Header present.
		assert "# Auto-generated by book-meta-fix" in out
		assert "# 2 books need review." in out

	def test_skips_ok_books(self):
		items = [
			(_meta(1), _diag(verdict=Verdict.OK), None, None),  # skipped
			(_meta(2), _diag(verdict=Verdict.NEEDS_REVIEW), None, None),  # kept
		]
		out = build_review(items)
		assert out.count("---") == 1
		assert "id: 2" in out

	def test_includes_auto_fixable_with_pre_filled_action(self):
		"""AUTO_FIXABLE books (e.g. C6 Word lock-file) are emitted and their
		diag.proposed["action"] is pre-filled so the user only confirms."""
		diag = _diag(category="C6", verdict=Verdict.AUTO_FIXABLE)
		diag.proposed = {"action": "delete", "reason": "word lockfile"}
		items = [(_meta(1, "~$doc"), diag, None, None)]
		out = build_review(items)
		assert out.count("---") == 1
		assert "action: delete" in out

	def test_header_count_matches_emitted(self):
		items = [(_meta(i), _diag(), None, None) for i in range(1, 4)]
		out = build_review(items)
		assert "# 3 books need review." in out
		assert out.count("---") == 3

	def test_unicode_preserved(self):
		items = [(_meta(1, title="Čas přílivu", author="Božena Němcová"), _diag(), None, None)]
		out = build_review(items)
		# No \uXXXX escapes — real Czech characters.
		assert "Čas přílivu" in out
		assert "Božena Němcová" in out


class TestParseReviewRoundTrip:
	def test_round_trip_multi_doc(self, tmp_path):
		items = [(_meta(1, "Alpha"), _diag(), None, None), (_meta(2, "Beta"), _diag(), None, None)]
		path = tmp_path / "review.yaml"
		path.write_text(build_review(items), encoding="utf-8")
		parsed = parse_review(path)
		assert len(parsed) == 2
		assert parsed[0].id == 1 and parsed[0].current["title"] == "Alpha"
		assert parsed[1].id == 2 and parsed[1].current["title"] == "Beta"

	def test_round_trip_preserves_user_action(self, tmp_path):
		# Hand-edit the file with an action, then parse it back.
		items = [(_meta(1, "Alpha"), _diag(), None, None)]
		path = tmp_path / "review.yaml"
		text = build_review(items)
		# Inject a user decision.
		text = text.replace("action: null", "action: accept")
		path.write_text(text, encoding="utf-8")
		parsed = parse_review(path)
		assert parsed[0].action == "accept"


class TestParseLegacySingleList:
	def test_reads_legacy_single_list_format(self, tmp_path):
		"""Old review.yaml files are a single YAML list (no --- separators).
		parse_review must still read them."""
		legacy = """# header
- id: 1
  path: a
  diagnosis: {category: C2, reason: r}
  current: {title: A}
  proposed: null
  action: null
- id: 2
  path: b
  diagnosis: {category: C2, reason: r}
  current: {title: B}
  proposed: null
  action: reject
"""
		path = tmp_path / "legacy.yaml"
		path.write_text(legacy, encoding="utf-8")
		parsed = parse_review(path)
		assert len(parsed) == 2
		assert parsed[0].id == 1
		assert parsed[1].action == "reject"

	def test_empty_file_returns_empty_list(self, tmp_path):
		path = tmp_path / "empty.yaml"
		path.write_text("# only comments\n", encoding="utf-8")
		assert parse_review(path) == []

	def test_mixed_multi_doc_and_list_documents(self, tmp_path):
		"""A stream where one doc is a list and another is a single dict — both
		must flatten into the parsed list (defensive against odd hybrids)."""
		hybrid = "---\n- id: 1\n  current: {title: A}\n---\nid: 2\ncurrent: {title: B}\n"
		path = tmp_path / "hybrid.yaml"
		path.write_text(hybrid, encoding="utf-8")
		parsed = parse_review(path)
		assert len(parsed) == 2
