"""Round-trip tests for review.yaml multi-document format and parsing.

Covers build_review (emits multi-doc), parse_review (reads multi-doc and legacy
single-list), and the format's backward compatibility.
"""
from __future__ import annotations

from book_meta_fix.enrichers import EnrichedMeta
from book_meta_fix.models import BookMeta, Confidence, Diagnosis, Verdict
from book_meta_fix.review import _build_current, _build_proposed, _header, build_review, parse_review


def _meta(calibre_id: int, title: str = "T", author: str = "A") -> BookMeta:
	return BookMeta(calibre_id=calibre_id, title=title, authors=[author], path=f"/lib/A/{title} ({calibre_id})")


def _diag(category: str = "C2", verdict: Verdict = Verdict.NEEDS_REVIEW) -> Diagnosis:
	return Diagnosis(category=category, reason="r", confidence=Confidence.HIGH, verdict=verdict)


class TestBuildReviewFormat:
	def test_emits_multi_document_with_separators(self):
		items = [(_meta(1), _diag(), None, None), (_meta(2), _diag(), None, None)]
		out = build_review(items)
		# Each entry prefixed by its own --- document marker.
		assert out.count("---") == 2
		# Header present.
		assert "# Auto-generated by book-meta-fix" in out
		assert "# 2 books need review." in out

	def test_skips_ok_books(self):
		items = [
			(_meta(1), _diag(verdict=Verdict.OK), None, None),  # skipped
			(_meta(2), _diag(verdict=Verdict.NEEDS_REVIEW), None, None),  # kept
		]
		out = build_review(items)
		assert out.count("---") == 1
		assert "id: 2" in out

	def test_includes_auto_fixable_with_pre_filled_action(self):
		"""AUTO_FIXABLE books (e.g. C6 Word lock-file) are emitted and their
		diag.proposed["action"] is pre-filled so the user only confirms."""
		diag = _diag(category="C6", verdict=Verdict.AUTO_FIXABLE)
		diag.proposed = {"action": "delete", "reason": "word lockfile"}
		items = [(_meta(1, "~$doc"), diag, None, None)]
		out = build_review(items)
		assert out.count("---") == 1
		assert "action: delete" in out

	def test_header_count_matches_emitted(self):
		items = [(_meta(i), _diag(), None, None) for i in range(1, 4)]
		out = build_review(items)
		assert "# 3 books need review." in out
		assert out.count("---") == 3

	def test_unicode_preserved(self):
		items = [(_meta(1, title="Čas přílivu", author="Božena Němcová"), _diag(), None, None)]
		out = build_review(items)
		# No \uXXXX escapes — real Czech characters.
		assert "Čas přílivu" in out
		assert "Božena Němcová" in out


class TestParseReviewRoundTrip:
	def test_round_trip_multi_doc(self, tmp_path):
		items = [(_meta(1, "Alpha"), _diag(), None, None), (_meta(2, "Beta"), _diag(), None, None)]
		path = tmp_path / "review.yaml"
		path.write_text(build_review(items), encoding="utf-8")
		parsed = parse_review(path)
		assert len(parsed) == 2
		assert parsed[0].id == 1 and parsed[0].current["title"] == "Alpha"
		assert parsed[1].id == 2 and parsed[1].current["title"] == "Beta"

	def test_round_trip_preserves_user_action(self, tmp_path):
		# Hand-edit the file with an action, then parse it back.
		items = [(_meta(1, "Alpha"), _diag(), None, None)]
		path = tmp_path / "review.yaml"
		text = build_review(items)
		# Inject a user decision.
		text = text.replace("action: null", "action: accept")
		path.write_text(text, encoding="utf-8")
		parsed = parse_review(path)
		assert parsed[0].action == "accept"


class TestParseLegacySingleList:
	def test_reads_legacy_single_list_format(self, tmp_path):
		"""Old review.yaml files are a single YAML list (no --- separators).
		parse_review must still read them."""
		legacy = """# header
- id: 1
  path: a
  diagnosis: {category: C2, reason: r}
  current: {title: A}
  proposed: null
  action: null
- id: 2
  path: b
  diagnosis: {category: C2, reason: r}
  current: {title: B}
  proposed: null
  action: reject
"""
		path = tmp_path / "legacy.yaml"
		path.write_text(legacy, encoding="utf-8")
		parsed = parse_review(path)
		assert len(parsed) == 2
		assert parsed[0].id == 1
		assert parsed[1].action == "reject"

	def test_empty_file_returns_empty_list(self, tmp_path):
		path = tmp_path / "empty.yaml"
		path.write_text("# only comments\n", encoding="utf-8")
		assert parse_review(path) == []

	def test_mixed_multi_doc_and_list_documents(self, tmp_path):
		"""A stream where one doc is a list and another is a single dict — both
		must flatten into the parsed list (defensive against odd hybrids)."""
		hybrid = "---\n- id: 1\n  current: {title: A}\n---\nid: 2\ncurrent: {title: B}\n"
		path = tmp_path / "hybrid.yaml"
		path.write_text(hybrid, encoding="utf-8")
		parsed = parse_review(path)
		assert len(parsed) == 2


def _enriched_with_cover() -> EnrichedMeta:
	"""An enriched hit that carries a cover_url plus a year, so proposed is
	guaranteed non-empty even when cover_url is gated out."""
	return EnrichedMeta(
		title="Some Title",
		authors=["Some Author"],
		year=2001,
		cover_url="https://example.com/cover.jpg",
		source="databazeknih",
	)


class TestCoverUrlProposalGate:
	"""cover_url must only land in `proposed` for C11 / MISSING_COVER books.

	Every enriched book carries a cover_url, but downloading is reserved for the
	cover-problem categories — otherwise apply would fetch covers for every
	metadata fix and the Covers report would never match apply's behaviour.
	"""

	def test_cover_url_proposed_for_c11(self):
		meta = _meta(1)
		diag = _diag(category="C11")
		proposed = _build_proposed(meta, None, _enriched_with_cover(), diag)
		assert proposed is not None
		assert proposed.get("cover_url") == "https://example.com/cover.jpg"

	def test_cover_url_proposed_for_missing_cover(self):
		meta = _meta(1)
		diag = _diag(category="MISSING_COVER")
		proposed = _build_proposed(meta, None, _enriched_with_cover(), diag)
		assert proposed is not None
		assert proposed.get("cover_url") == "https://example.com/cover.jpg"

	def test_cover_url_not_proposed_for_non_cover_category(self):
		"""A C2 (metadata) book keeps its enriched year but NOT the cover_url."""
		meta = _meta(1)
		diag = _diag(category="C2")
		proposed = _build_proposed(meta, None, _enriched_with_cover(), diag)
		assert proposed is not None
		assert "cover_url" not in proposed
		# Other enriched fields are still proposed.
		assert proposed.get("year") == 2001

	def test_cover_url_not_proposed_without_diag(self):
		"""No diagnosis available → be conservative, don't propose a cover."""
		meta = _meta(1)
		proposed = _build_proposed(meta, None, _enriched_with_cover(), None)
		assert proposed is not None
		assert "cover_url" not in proposed

	def test_cover_url_proposed_when_c11_is_additional(self):
		"""A book whose primary issue is NOT a cover but that also has a
		generated cover (C11 in diag.additional) still gets cover_url proposed —
		so apply can fix both the title and the cover in one pass."""
		meta = _meta(1)
		diag = _diag(category="C2")  # primary is a title issue
		diag.additional = [_diag(category="C11")]
		proposed = _build_proposed(meta, None, _enriched_with_cover(), diag)
		assert proposed is not None
		assert proposed.get("cover_url") == "https://example.com/cover.jpg"

	def test_entry_exposes_diagnoses_list(self):
		"""When a book carries additional diagnoses, the review entry exposes
		the full list (primary first) so apply sees every problem."""
		from book_meta_fix.review import _entry_dict

		meta = _meta(1)
		diag = _diag(category="C2")
		diag.additional = [_diag(category="C11")]
		entry = _entry_dict(meta, diag, None, None, None, library_root=None)
		assert entry["diagnosis"]["category"] == "C2"  # primary stays
		cats = [d["category"] for d in entry["diagnoses"]]
		assert cats == ["C2", "C11"]

	def test_entry_no_diagnoses_key_for_single_issue(self):
		"""A single-issue book keeps the legacy shape (no `diagnoses` key)."""
		from book_meta_fix.review import _entry_dict

		meta = _meta(1)
		entry = _entry_dict(meta, _diag(), None, None, None, library_root=None)
		assert "diagnoses" not in entry


class TestLanguageAndDescriptionProposal:
	"""language was fetched by every enricher but historically never proposed
	(the apply branch existed with nothing feeding it); description was dropped
	for every source that returns a real annotation. Both must now flow."""

	def test_language_proposed_when_differing(self):
		meta = _meta(1)
		meta.language = "cs"
		enr = EnrichedMeta(language="sk", source="google_books")
		proposed = _build_proposed(meta, None, enr, _diag())
		assert proposed is not None
		assert proposed["language"] == "sk"

	def test_language_proposed_when_missing(self):
		enr = EnrichedMeta(language="cs", source="llm:high")
		proposed = _build_proposed(_meta(1), None, enr, _diag())
		assert proposed["language"] == "cs"

	def test_language_not_proposed_when_equal(self):
		meta = _meta(1)
		meta.language = "cs"
		enr = EnrichedMeta(language="cs", year=2001, source="databazeknih")
		proposed = _build_proposed(meta, None, enr, _diag())
		assert "language" not in proposed
		# The year still is (guards against an empty-proposed shortcut).
		assert proposed["year"] == 2001

	def test_description_from_real_source(self):
		enr = EnrichedMeta(description="Anotace knihy.", source="databazeknih")
		proposed = _build_proposed(_meta(1), None, enr, _diag())
		assert proposed["description"] == "Anotace knihy."

	def test_legie_description_not_proposed(self):
		"""legie.info stashes the original title in the description field — a
		cross-check aid, not an annotation; it must not reach the book."""
		enr = EnrichedMeta(description="originál: Foundation", source="legie")
		proposed = _build_proposed(_meta(1), None, enr, _diag())
		assert proposed is None or "description" not in proposed

	def test_llm_description_stays_reasoning(self):
		"""The LLM's description field carries reasoning — shown as
		``reasoning``, never written as the book's annotation."""
		enr = EnrichedMeta(description="the model's reasoning", series="Nadace", source="llm:high")
		proposed = _build_proposed(_meta(1), None, enr, _diag())
		assert proposed["reasoning"] == "the model's reasoning"
		assert "description" not in proposed


class TestBuildCurrentSeries:
	def test_includes_series_fields(self):
		meta = _meta(1)
		meta.series = [{"name": "Zaklínač", "index": "8"}]
		cur = _build_current(meta)
		assert cur["series"] == "Zaklínač"
		assert cur["series_index"] == "8"

	def test_omits_series_when_absent(self):
		cur = _build_current(_meta(1))
		assert "series" not in cur
		assert "series_index" not in cur


class TestHeaderDocumentsActions:
	def test_header_lists_keep_action(self):
		"""The review.yaml header must document the ``keep`` action so a human
		editor knows it exists (and that it is retained, not pruned)."""
		h = _header(3)
		assert "keep" in h
		# All canonical actions are documented.
		for a in ("accept", "reject", "swap", "edit", "delete", "keep"):
			assert a in h
