"""YAML review file generation and parsing.

The review.yaml is the primary human-in-the-loop mechanism. It lists books
flagged as NEEDS_REVIEW with their current metadata, our proposed fix, and an
`action` field the human fills in (accept/delete/keep). The user adjusts the
proposal by editing the `proposed` values directly (a `null` value deletes
the field); there is no separate edit block.

Format: a multi-document YAML stream. Each book is its own top-level document
prefixed by `---`, which lets ReviewWriter append entries one-at-a-time (Unix
pipe style) instead of rewriting the whole file on every flush. `parse_review`
accepts both the multi-document stream and the legacy single-list form.

Generator: build_review() takes a list of (meta, diagnosis, extracted, enriched)
	tuples and emits a YAML string.
Parser: parse_review() reads a (possibly human-edited) YAML back into a list
	of ReviewItem dataclasses ready for the writer to apply.
"""
from __future__ import annotations

import logging
import os
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path
from typing import Any, Literal

import yaml

from .detectors import all_diagnoses
from .extractors import ExtractedMeta
from .i18n import _
from .models import BookMeta, Diagnosis

log = logging.getLogger(__name__)

Action = Literal["accept", "delete", "keep"]


@dataclass
class ReviewItem:
	"""One book entry in the review file."""

	id: int | None  # calibre_id (informational, parsed from folder name)
	uuid: str | None  # bmf identity — the carry-over/prune key
	path: str  # relative to library root, for human readability
	diagnosis: dict[str, Any]
	current: dict[str, Any]
	# All diagnoses (primary first). Absent in older review.yaml files; parse_review
	# falls back to [diagnosis] so callers can always read item.diagnoses.
	diagnoses: list[dict[str, Any]] = field(default_factory=list)
	proposed: dict[str, Any] | None = None
	# Human decisions:
	action: Action | None = None
	# User-confirmed OK: apply writes this into metadata.json (the durable
	# skip mark analyze honours) and routes the book to the OK path even when
	# detectors still complain. Orthogonal to `action` — composable as
	# "accept + verified" (fix AND close) or verified alone (close as-is).
	verified: bool = False
	notes: str | None = None


def _header(count: int) -> str:
	"""The leading comment block placed at the top of review.yaml.

	Localized as ONE msgid (translated block); the action keywords
	(accept/reject/...) are a stable YAML API and must stay untranslated.
	"""
	return "# " + _(
		"Auto-generated by book-meta-fix on {date}\n"
		"# {count} books need review.\n"
		"# For each entry, set `action` to one of:\n"
		"#   accept  - apply `proposed` (edit the values to override the\n"
		"#             analyzer; a `null` value DELETES the field)\n"
		"#   delete  - remove the book folder (C6 ~$ Word lock-file; tar.gz-backed)\n"
		"#   keep    - apply like accept, but the entry stays in this file\n"
		"# Set `verified: true` to mark a book OK: apply stores the flag in\n"
		"# metadata.json, later analyze runs skip the book and apply moves it\n"
		"# to the target folder (`proposed.location`) like a clean book.\n"
		"# Then run: bmf apply review.yaml\n"
	).format(date=date.today().isoformat(), count=count) + "\n"


def _relative_path(meta: BookMeta, library_root: Path | None) -> str:
	"""Book path, made relative to library_root for readability when possible."""
	if library_root is None:
		return meta.path
	try:
		return str(Path(meta.path).relative_to(library_root))
	except ValueError:
		return meta.path


def _build_current(meta: BookMeta) -> dict[str, Any]:
	"""Build the `current` block for a review entry, dropping None values."""
	series_name, series_index = meta.series_pair()
	current = {
		"author": meta.authors[0] if meta.authors else None,
		"authors": meta.authors if len(meta.authors) > 1 else None,
		"title": meta.title,
		"isbn": meta.isbn,
		"year": meta.year,
		"publisher": meta.publisher,
		"language": meta.language,
		"series": series_name or None,
		"series_index": series_index or None,
	}
	return {k: v for k, v in current.items() if v is not None}


def _entry_dict(meta: BookMeta, diag: Diagnosis, extracted: Any, enriched: Any, prior: dict | None, library_root: Path | None) -> dict[str, Any]:
	"""Build a single review entry dict from a result tuple's components.

	*prior* (when present) carries user edits (action/edited/notes) to preserve.
	AUTO_FIXABLE detectors may carry an explicit action on diag.proposed (e.g.
	C6 Word lock-file -> {"action": "delete"}); it is pre-filled so the user
	only has to confirm, unless a prior decision overrides it.
	"""
	proposed = _build_proposed(meta, extracted, enriched, diag)
	diag_proposed = getattr(diag, "proposed", None) or {}
	action = diag_proposed.get("action") if diag.verdict.value == "AUTO_FIXABLE" else None
	if diag_proposed and diag.verdict.value == "AUTO_FIXABLE":
		extra = {k: v for k, v in diag_proposed.items() if k != "action"}
		if extra:
			proposed = {**(proposed or {}), **extra}
	entry: dict[str, Any] = {
		"id": meta.calibre_id,
		"uuid": meta.uuid,
		"path": _relative_path(meta, library_root),
		"diagnosis": {
			"category": diag.category,
			"reason": diag.reason,
			"confidence": diag.confidence.value,
		},
		"current": _build_current(meta),
		"proposed": proposed,
		"action": action,
	}
	# When the book has more than one diagnosis, expose the full list so apply
	# and the human reviewer see every problem (e.g. C2 + C11). Single-issue
	# books keep the legacy shape (just `diagnosis`); parse_review synthesises
	# the list when absent.
	if diag.additional:
		entry["diagnoses"] = [
			{"category": d.category, "reason": d.reason, "confidence": d.confidence.value}
			for d in all_diagnoses(diag)
		]
	if prior is not None:
		if prior.get("action") is not None:
			entry["action"] = prior["action"]
			# The decision was made against the PRIOR proposal — carry it
			# verbatim (null = field deletes included) so a fresh run cannot
			# silently change what accept would apply.
			entry["proposed"] = prior.get("proposed")
		if prior.get("verified"):
			entry["verified"] = True
		if prior.get("notes"):
			entry["notes"] = prior["notes"]
	return entry


def _render_entry(entry: dict[str, Any]) -> str:
	"""Render one review entry dict as a single multi-document YAML chunk.

	Output is a leading `---` newline + the YAML block (no trailing `---`),
	suitable for streaming append. Block style, unicode preserved, insertion-
	order keys.
	"""
	body = yaml.safe_dump(entry, allow_unicode=True, sort_keys=False, default_flow_style=False, width=120)
	return f"---\n{body}"


def build_review(
	items: list[tuple],
	*,
	library_root: Path | None = None,
) -> str:
	"""Build a review.yaml string from detected books.

	*items* is a list of (meta, diagnosis, extracted, enriched) tuples where
	`extracted` and `enriched` may be None. NEEDS_REVIEW, UNFIXABLE and
	AUTO_FIXABLE books are emitted (the last may carry a pre-filled action).

	Tuples may carry an optional 5th element: a prior-entry dict with user
	edits (action / edited / notes) to preserve across re-runs.

	Output is a multi-document YAML stream (each entry prefixed by `---`).
	"""
	entries: list[dict] = []
	for item in items:
		meta, diag, extracted, enriched = item[0], item[1], item[2], item[3]
		prior = item[4] if len(item) > 4 else None
		if diag.verdict.value not in ("NEEDS_REVIEW", "UNFIXABLE", "AUTO_FIXABLE"):
			continue
		entries.append(_entry_dict(meta, diag, extracted, enriched, prior, library_root))

	header = _header(len(entries))
	body = "\n".join(_render_entry(e) for e in entries)
	if body:
		body += "\n"
	return header + body


# Categories whose diagnosis is specifically about a cover problem. A
# cover_url from an enricher is only acted upon (proposed + downloaded) for
# these — every enriched book carries a cover_url, but we must not download
# covers for books whose diagnosis is about metadata, not the cover.
_COVER_CATEGORIES = ("C11", "MISSING_COVER")


def _build_proposed(
	meta: BookMeta, extracted: ExtractedMeta | None, enriched: Any, diag: Any = None
) -> dict[str, Any] | None:
	"""Build a proposed-fix dict from extracted content + online enrichment.

	Preference: extracted (book content) > enriched (online) > None.
	Returns None if we have no better suggestion than current.

	*diag* (the Diagnosis) gates the ``cover_url`` proposal: it is emitted only
	for C11 (generated placeholder) / MISSING_COVER books, since cover_url
	otherwise rides along on every enriched book and would mislead the user
	into thinking a cover change is part of a metadata fix.
	"""
	proposed: dict[str, Any] = {}
	source_parts: list[str] = []

	if extracted is not None:
		if extracted.isbn and extracted.isbn != meta.isbn:
			proposed["isbn"] = extracted.isbn
			source_parts.append("embedded")
		if extracted.isbn_from_text and not extracted.isbn and not meta.isbn:
			proposed["isbn"] = extracted.isbn_from_text
			source_parts.append("content")
		# Use extracted title/author only if DB looks broken (filename/mojibake)
		if extracted.title and _looks_better(extracted.title, meta.title):
			proposed["title"] = extracted.title
			source_parts.append("embedded")
		if extracted.authors and _looks_better(extracted.authors[0], meta.authors[0] if meta.authors else ""):
			proposed["author"] = extracted.authors[0]
			source_parts.append("embedded")

	if enriched is not None:
		# LLM proposals and databazeknih hits are pre-vetted: trust their
		# title/author without the _looks_better gate. The LLM already reasoned
		# about the right value; databazeknih already fuzzy-matched the book
		# (score >= 70) before returning it, so a title it returns IS the title
		# of the matched book — even if the DB title (a filename-as-title C2
		# case) does not look "broken" to _looks_better.
		# identity_confirmed (verified against the book's content) is trusted
		# like databazeknih/llm:high: we know which book it is, so its title/
		# author are proposed even if the current metadata doesn't look broken.
		trust_blindly = enriched.source.startswith("llm:") or enriched.source == "databazeknih" or getattr(enriched, "identity_confirmed", False)
		if enriched.title and "title" not in proposed and (trust_blindly or _looks_better(enriched.title, meta.title)):
			proposed["title"] = enriched.title
			source_parts.append(enriched.source)
		if enriched.authors and "author" not in proposed:
			# Pick the first non-placeholder author
			real_author = next((a for a in enriched.authors if a and a not in ("Neznamy", "Unknown", "anonym", "Anonymous")), None)
			if real_author and (trust_blindly or _looks_better(real_author, meta.authors[0] if meta.authors else "")):
				proposed["author"] = real_author
				# If LLM returned multiple authors, expose them all
				if len(enriched.authors) > 1:
					proposed["authors"] = enriched.authors
				source_parts.append(enriched.source)
		if enriched.isbn and "isbn" not in proposed:
			proposed["isbn"] = enriched.isbn
			source_parts.append(enriched.source)
		if enriched.year and (not meta.year or enriched.year != meta.year):
			proposed["year"] = enriched.year
			source_parts.append(enriched.source)
		if enriched.publisher and (not meta.publisher or enriched.publisher != meta.publisher):
			proposed["publisher"] = enriched.publisher
			source_parts.append(enriched.source)
		# Language: fetched by Google Books / OpenLibrary / databazeknih / LLM,
		# but historically never proposed — the apply branch existed with
		# nothing feeding it. Same pattern as publisher: propose on difference.
		if enriched.language and (not meta.language or enriched.language != meta.language):
			proposed["language"] = enriched.language
			source_parts.append(enriched.source)
		# Description (annotation) — only from sources that return a REAL
		# annotation. legie.info stashes the original title in the field (a
		# cross-check aid, not a description) and for LLM sources the field
		# carries the model's reasoning (proposed separately as "reasoning"
		# below); neither may be written into the book.
		if (
			enriched.description
			and enriched.source != "legie"
			and not enriched.source.startswith("llm")
			and (not meta.description or enriched.description != meta.description)
		):
			proposed["description"] = enriched.description
			source_parts.append(enriched.source)
		# cover_url only when the book has a cover diagnosis among ANY of its
		# diagnoses (primary or additional) — every enriched book carries a
		# cover_url, but downloading is reserved for C11 / MISSING_COVER. A book
		# whose primary issue is C2 but that also has a generated cover (C11 in
		# diag.additional) should still get its cover proposed.
		if enriched.cover_url and any(d.category in _COVER_CATEGORIES for d in all_diagnoses(diag)):
			proposed["cover_url"] = enriched.cover_url
			source_parts.append(enriched.source)
		# Series (mostly from LLM / obalkyknih — DB usually lacks it)
		if getattr(enriched, "series", None) and enriched.series:
			proposed["series"] = enriched.series
			if getattr(enriched, "series_index", None):
				proposed["series_index"] = enriched.series_index
			source_parts.append(enriched.source)
		# Genres (LLM-derived literary tags)
		if getattr(enriched, "genres", None) and enriched.genres:
			proposed["genres"] = enriched.genres
			source_parts.append(enriched.source)
		# LLM reasoning — show as a comment-like field for the human reviewer
		if getattr(enriched, "description", None) and enriched.source.startswith("llm"):
			proposed["reasoning"] = enriched.description

	# C1 (author/title swapped): when nothing better was found, the analyzer
	# proposes the swap itself — deterministic, no network. `swap` used to be
	# a review ACTION applied at write time; now it is an ordinary proposal
	# the user reviews (and can adjust) before accepting.
	if diag is not None and any(d.category == "C1" for d in all_diagnoses(diag)):
		if meta.title and meta.authors:
			if "title" not in proposed and meta.authors[0]:
				proposed["title"] = meta.authors[0]
				source_parts.append("swap")
			if "author" not in proposed:
				proposed["author"] = meta.title
				source_parts.append("swap")
	# C13 (location mismatch): surface the target folder computed by the
	# detector. INFORMATIONAL only — apply recomputes the destination from
	# the FINAL metadata (the user may fix author/title in the same pass),
	# and `_apply_fields` deliberately ignores the `location` key. Suppressed
	# for EMPTY_BOOK records: their real destination is needfix/empty/, so a
	# pattern-path proposal would be misleading.
	if diag is not None and not any(d.category == "EMPTY_BOOK" for d in all_diagnoses(diag)):
		for d in all_diagnoses(diag):
			if d.category == "C13" and d.proposed and d.proposed.get("location"):
				if "location" not in proposed:
					proposed["location"] = d.proposed["location"]
					source_parts.append("location")
				break
	if source_parts:
		proposed["source"] = "+".join(sorted(set(source_parts)))
		return proposed
	return None


def _looks_better(candidate: str | None, current: str | None) -> bool:
	"""Heuristic: does *candidate* look more correct than *current*?

	A candidate is "better" if the current value has obvious corruption
	(underscores, extensions, mojibake) and the candidate does not.
	"""
	if not candidate:
		return False
	if not current:
		return True
	# Current is suspect if it has filename/encoding artifacts
	current_bad = ("_" in current or ".epub" in current.lower() or ".pdb" in current.lower() or ".mobi" in current.lower() or ".azw" in current.lower() or ".azw3" in current.lower() or ".prc" in current.lower() or ".pdf" in current.lower() or any(ord(c) > 0x2000 and c not in "„“”‘’–—" for c in current))
	candidate_bad = ("_" in candidate or any(ord(c) > 0x2000 and c not in "„“”‘’–—" for c in candidate))
	return current_bad and not candidate_bad


def _load_raw_entries(path: str | Path) -> list[dict[str, Any]]:
	"""Read all entry dicts from a review file (multi-doc or legacy list form).

	``safe_load_all`` handles both: a single-list file yields one document (the
	list), which we flatten; a multi-doc stream yields one dict per document.
	Non-dict/non-list documents raise ValueError, matching parse_review.
	"""
	text = Path(path).read_text(encoding="utf-8")
	docs = list(yaml.safe_load_all(text))
	if not docs:
		return []
	raw_entries: list[Any] = []
	for doc in docs:
		if doc is None:
			continue
		if isinstance(doc, list):
			raw_entries.extend(doc)
		elif isinstance(doc, dict):
			raw_entries.append(doc)
		else:
			raise ValueError(f"review file must contain YAML dicts/lists, got {type(doc).__name__}")
	return [_migrate_entry(e) for e in raw_entries if isinstance(e, dict)]


def _migrate_entry(e: dict[str, Any]) -> dict[str, Any]:
	"""Migrate a legacy review entry to the current shape (in place).

	- ``edited`` block: merged over ``proposed`` and dropped — the editor's
	  field values (``null`` = field delete) live in ``proposed`` itself now.
	- ``action: edit``: becomes ``accept`` (apply the merged proposal).
	- ``action: reject``/``swap``: reset to pending — those actions no longer
	  exist. A C1 swap is re-proposed by the analyzer instead; a "reject" was
	  an explicit no-op (the entry simply stays undecided).
	"""
	edited = e.get("edited")
	if edited:
		e["proposed"] = {**(e.get("proposed") or {}), **edited}
		del e["edited"]
	a = e.get("action")
	if a == "edit":
		e["action"] = "accept"
	elif a in ("reject", "swap"):
		e["action"] = None
	return e


def parse_review(path: str | Path) -> list[ReviewItem]:
	"""Parse a (possibly human-edited) review.yaml back into ReviewItems.

	Accepts both:
	  - multi-document YAML stream (current format: each book prefixed by `---`)
	  - legacy single-list form (one YAML list of dicts)

	Legacy entries are migrated on load (see :func:`_migrate_entry`), so
	callers only ever see the current shape.
	"""
	return [
		ReviewItem(
			id=entry.get("id"),
			uuid=entry.get("uuid"),
			path=entry.get("path", ""),
			diagnosis=entry.get("diagnosis") or {},
			# diagnoses falls back to the single primary diagnosis for older
			# entries that only carry `diagnosis`.
			diagnoses=entry.get("diagnoses") or ([entry.get("diagnosis")] if entry.get("diagnosis") else []),
			current=entry.get("current") or {},
			proposed=entry.get("proposed"),
			action=entry.get("action"),
			verified=bool(entry.get("verified")),
			notes=entry.get("notes"),
		)
		for entry in _load_raw_entries(path)
	]


def prune_review(path: str | Path, drop_uuids: set) -> int:
	"""Rewrite review.yaml in place, dropping entries whose ``uuid`` is in
	*drop_uuids*. Returns the number of entries kept.

	Used by apply_review to remove successfully-applied entries so the file
	reflects only remaining work (and subsequent apply runs don't re-process
	already-committed books). Entries without a ``uuid`` (e.g. leftover legacy
	entries from before uuid keying) are always kept — they cannot be matched
	safely. Re-rendered via the standard renderer, so inline comments are not
	preserved (the file is otherwise machine-generated).
	"""
	entries = _load_raw_entries(path)
	kept = [e for e in entries if e.get("uuid") is None or e.get("uuid") not in drop_uuids]
	header = _header(len(kept))
	body = "\n".join(_render_entry(e) for e in kept)
	if body:
		body += "\n"
	Path(path).write_text(header + body, encoding="utf-8")
	return len(kept)


def update_paths(path: str | Path, moves: dict[str, str]) -> int:
	"""Rewrite the ``path`` field of entries whose uuid moved (kept entries).

	After apply relocates a folder, a retained (``action: keep``) entry would
	otherwise point at the OLD path forever: analyze skips keep entries only
	in the freeze model — here the entry survives with a stale path, and the
	next ``bmf apply`` would fail it with "folder not found". Accept entries
	are pruned instead, so only keep entries (and any other survivor) need
	this. *moves* maps uuid → new path relative to the library root. Atomic
	(tmp + os.replace); returns the number of entries updated.
	"""
	if not moves:
		return 0
	entries = _load_raw_entries(path)
	changed = 0
	for e in entries:
		new_path = moves.get(e.get("uuid"))
		if new_path is not None and e.get("path") != new_path:
			e["path"] = new_path
			changed += 1
	if not changed:
		return 0
	header = _header(len(entries))
	body = "\n".join(_render_entry(e) for e in entries)
	if body:
		body += "\n"
	p = Path(path)
	tmp = p.with_suffix(p.suffix + ".tmp")
	tmp.write_text(header + body, encoding="utf-8")
	os.replace(tmp, p)
	return changed
