"""YAML review file generation and parsing.

The review.yaml is the primary human-in-the-loop mechanism. It lists books
flagged as NEEDS_REVIEW with their current metadata, our proposed fix, and an
`action` field the human fills in (accept/reject/swap/edit).

Format: a multi-document YAML stream. Each book is its own top-level document
prefixed by `---`, which lets ReviewWriter append entries one-at-a-time (Unix
pipe style) instead of rewriting the whole file on every flush. `parse_review`
accepts both the multi-document stream and the legacy single-list form.

Generator: build_review() takes a list of (meta, diagnosis, extracted, enriched)
	tuples and emits a YAML string.
Parser: parse_review() reads a (possibly human-edited) YAML back into a list
	of ReviewItem dataclasses ready for the writer to apply.
"""
from __future__ import annotations

import logging
from dataclasses import asdict, dataclass, field
from datetime import date
from pathlib import Path
from typing import Any, Literal

import yaml

from .extractors import ExtractedMeta
from .models import BookMeta, Diagnosis

log = logging.getLogger(__name__)

Action = Literal["accept", "reject", "swap", "edit", "delete"]


@dataclass
class ReviewItem:
	"""One book entry in the review file."""

	id: int | None
	path: str  # relative to library root, for human readability
	diagnosis: dict[str, Any]
	current: dict[str, Any]
	proposed: dict[str, Any] | None = None
	# Human-edited fields:
	action: Action | None = None
	edited: dict[str, Any] | None = None
	notes: str | None = None


def _header(count: int) -> str:
	"""The leading comment block placed at the top of review.yaml."""
	return (
		f"# Auto-generated by book-meta-fix on {date.today().isoformat()}\n"
		f"# {count} books need review.\n"
		f"# For each entry, set `action` to one of:\n"
		f"#   accept  - apply `proposed` as-is\n"
		f"#   reject  - leave unchanged\n"
		f"#   swap    - swap author <-> title (for C1 cases)\n"
		f"#   edit    - apply fields under `edited` (uncomment and modify)\n"
		f"#   delete  - remove the book folder (C6 ~$ Word lock-file; tar.gz-backed)\n"
		f"# Then run: bmf apply review.yaml\n"
		f"\n"
	)


def _relative_path(meta: BookMeta, library_root: Path | None) -> str:
	"""Book path, made relative to library_root for readability when possible."""
	if library_root is None:
		return meta.path
	try:
		return str(Path(meta.path).relative_to(library_root))
	except ValueError:
		return meta.path


def _build_current(meta: BookMeta) -> dict[str, Any]:
	"""Build the `current` block for a review entry, dropping None values."""
	current = {
		"author": meta.authors[0] if meta.authors else None,
		"authors": meta.authors if len(meta.authors) > 1 else None,
		"title": meta.title,
		"isbn": meta.isbn,
		"year": meta.year,
		"publisher": meta.publisher,
		"language": meta.language,
	}
	return {k: v for k, v in current.items() if v is not None}


def _entry_dict(meta: BookMeta, diag: Diagnosis, extracted: Any, enriched: Any, prior: dict | None, library_root: Path | None) -> dict[str, Any]:
	"""Build a single review entry dict from a result tuple's components.

	*prior* (when present) carries user edits (action/edited/notes) to preserve.
	AUTO_FIXABLE detectors may carry an explicit action on diag.proposed (e.g.
	C6 Word lock-file -> {"action": "delete"}); it is pre-filled so the user
	only has to confirm, unless a prior decision overrides it.
	"""
	proposed = _build_proposed(meta, extracted, enriched)
	diag_proposed = getattr(diag, "proposed", None) or {}
	action = diag_proposed.get("action") if diag.verdict.value == "AUTO_FIXABLE" else None
	if diag_proposed and diag.verdict.value == "AUTO_FIXABLE":
		extra = {k: v for k, v in diag_proposed.items() if k != "action"}
		if extra:
			proposed = {**(proposed or {}), **extra}
	entry: dict[str, Any] = {
		"id": meta.calibre_id,
		"path": _relative_path(meta, library_root),
		"diagnosis": {
			"category": diag.category,
			"reason": diag.reason,
			"confidence": diag.confidence.value,
		},
		"current": _build_current(meta),
		"proposed": proposed,
		"action": action,
	}
	if prior is not None:
		if prior.get("action") is not None:
			entry["action"] = prior["action"]
		if prior.get("edited"):
			entry["edited"] = prior["edited"]
		if prior.get("notes"):
			entry["notes"] = prior["notes"]
	return entry


def _render_entry(entry: dict[str, Any]) -> str:
	"""Render one review entry dict as a single multi-document YAML chunk.

	Output is a leading `---` newline + the YAML block (no trailing `---`),
	suitable for streaming append. Block style, unicode preserved, insertion-
	order keys.
	"""
	body = yaml.safe_dump(entry, allow_unicode=True, sort_keys=False, default_flow_style=False, width=120)
	return f"---\n{body}"


def build_review(
	items: list[tuple],
	*,
	library_root: Path | None = None,
) -> str:
	"""Build a review.yaml string from detected books.

	*items* is a list of (meta, diagnosis, extracted, enriched) tuples where
	`extracted` and `enriched` may be None. NEEDS_REVIEW, UNFIXABLE and
	AUTO_FIXABLE books are emitted (the last may carry a pre-filled action).

	Tuples may carry an optional 5th element: a prior-entry dict with user
	edits (action / edited / notes) to preserve across re-runs.

	Output is a multi-document YAML stream (each entry prefixed by `---`).
	"""
	entries: list[dict] = []
	for item in items:
		meta, diag, extracted, enriched = item[0], item[1], item[2], item[3]
		prior = item[4] if len(item) > 4 else None
		if diag.verdict.value not in ("NEEDS_REVIEW", "UNFIXABLE", "AUTO_FIXABLE"):
			continue
		entries.append(_entry_dict(meta, diag, extracted, enriched, prior, library_root))

	header = _header(len(entries))
	body = "\n".join(_render_entry(e) for e in entries)
	if body:
		body += "\n"
	return header + body


def _build_proposed(
	meta: BookMeta, extracted: ExtractedMeta | None, enriched: Any
) -> dict[str, Any] | None:
	"""Build a proposed-fix dict from extracted content + online enrichment.

	Preference: extracted (book content) > enriched (online) > None.
	Returns None if we have no better suggestion than current.
	"""
	proposed: dict[str, Any] = {}
	source_parts: list[str] = []

	if extracted is not None:
		if extracted.isbn and extracted.isbn != meta.isbn:
			proposed["isbn"] = extracted.isbn
			source_parts.append("embedded")
		if extracted.isbn_from_text and not extracted.isbn and not meta.isbn:
			proposed["isbn"] = extracted.isbn_from_text
			source_parts.append("content")
		# Use extracted title/author only if DB looks broken (filename/mojibake)
		if extracted.title and _looks_better(extracted.title, meta.title):
			proposed["title"] = extracted.title
			source_parts.append("embedded")
		if extracted.authors and _looks_better(extracted.authors[0], meta.authors[0] if meta.authors else ""):
			proposed["author"] = extracted.authors[0]
			source_parts.append("embedded")

	if enriched is not None:
		# LLM proposals are pre-vetted: trust them without _looks_better gate.
		# The LLM already decided the new value is better than current.
		trust_blindly = enriched.source.startswith("llm:")
		if enriched.title and "title" not in proposed and (trust_blindly or _looks_better(enriched.title, meta.title)):
			proposed["title"] = enriched.title
			source_parts.append(enriched.source)
		if enriched.authors and "author" not in proposed:
			# Pick the first non-placeholder author
			real_author = next((a for a in enriched.authors if a and a not in ("Neznamy", "Unknown", "anonym", "Anonymous")), None)
			if real_author and (trust_blindly or _looks_better(real_author, meta.authors[0] if meta.authors else "")):
				proposed["author"] = real_author
				# If LLM returned multiple authors, expose them all
				if len(enriched.authors) > 1:
					proposed["authors"] = enriched.authors
				source_parts.append(enriched.source)
		if enriched.isbn and "isbn" not in proposed:
			proposed["isbn"] = enriched.isbn
			source_parts.append(enriched.source)
		if enriched.year and (not meta.year or enriched.year != meta.year):
			proposed["year"] = enriched.year
			source_parts.append(enriched.source)
		if enriched.publisher and (not meta.publisher or enriched.publisher != meta.publisher):
			proposed["publisher"] = enriched.publisher
			source_parts.append(enriched.source)
		if enriched.cover_url:
			proposed["cover_url"] = enriched.cover_url
			source_parts.append(enriched.source)
		# Series (mostly from LLM / obalkyknih — DB usually lacks it)
		if getattr(enriched, "series", None) and enriched.series:
			proposed["series"] = enriched.series
			if getattr(enriched, "series_index", None):
				proposed["series_index"] = enriched.series_index
			source_parts.append(enriched.source)
		# Genres (LLM-derived literary tags)
		if getattr(enriched, "genres", None) and enriched.genres:
			proposed["genres"] = enriched.genres
			source_parts.append(enriched.source)
		# LLM reasoning — show as a comment-like field for the human reviewer
		if getattr(enriched, "description", None) and enriched.source.startswith("llm"):
			proposed["reasoning"] = enriched.description

	if source_parts:
		proposed["source"] = "+".join(sorted(set(source_parts)))
		return proposed
	return None


def _looks_better(candidate: str | None, current: str | None) -> bool:
	"""Heuristic: does *candidate* look more correct than *current*?

	A candidate is "better" if the current value has obvious corruption
	(underscores, extensions, mojibake) and the candidate does not.
	"""
	if not candidate:
		return False
	if not current:
		return True
	# Current is suspect if it has filename/encoding artifacts
	current_bad = ("_" in current or ".epub" in current.lower() or ".pdb" in current.lower() or any(ord(c) > 0x2000 and c not in "„“”‘’–—" for c in current))
	candidate_bad = ("_" in candidate or any(ord(c) > 0x2000 and c not in "„“”‘’–—" for c in candidate))
	return current_bad and not candidate_bad


def parse_review(path: str | Path) -> list[ReviewItem]:
	"""Parse a (possibly human-edited) review.yaml back into ReviewItems.

	Accepts both:
	  - multi-document YAML stream (current format: each book prefixed by `---`)
	  - legacy single-list form (one YAML list of dicts)

	`safe_load_all` handles both: a single-list file yields one document (the
	list), which we flatten; a multi-doc stream yields one dict per document.
	"""
	text = Path(path).read_text(encoding="utf-8")
	docs = list(yaml.safe_load_all(text))
	if not docs:
		return []
	# Flatten: a single-list document (one list) becomes its items; individual
	# dict documents (multi-doc stream) are collected directly.
	raw_entries: list[Any] = []
	for doc in docs:
		if doc is None:
			continue
		if isinstance(doc, list):
			raw_entries.extend(doc)
		elif isinstance(doc, dict):
			raw_entries.append(doc)
		else:
			raise ValueError(f"review file must contain YAML dicts/lists, got {type(doc).__name__}")
	items: list[ReviewItem] = []
	for entry in raw_entries:
		if not isinstance(entry, dict):
			continue
		items.append(
			ReviewItem(
				id=entry.get("id"),
				path=entry.get("path", ""),
				diagnosis=entry.get("diagnosis") or {},
				current=entry.get("current") or {},
				proposed=entry.get("proposed"),
				action=entry.get("action"),
				edited=entry.get("edited"),
				notes=entry.get("notes"),
			)
		)
	return items
